version: '3.8'

services:
  app:
    # image: 'ghcr.io/ogharuki/job-offers:latest'
    image: 'job-offers:latest'
    container_name: app
    depends_on:
      - db
    restart: on-failure
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/JobOffers
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    volumes:
      - ./app-data:/app/data
      - ./logs:/app/data/logs
    ports:
      - "8080:8080"

  db:
    # image: 'ghcr.io/ogharuki/postgres:latest'
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=JobOffers
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
    app-data:
    db-data:
